# ******************************************************************************************************************
#
# Dette er en auto-generert fil; endringer gjøres i templates/.github/workflows/bygg_branch.yml
# Kjør deretter ' make generate-files' for oppdatering av workflow hos prosjekter
#
# ******************************************************************************************************************

name: Bygg branch

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!main'

jobs:
  bygg:
    permissions:
      packages: "write"
      id-token: "write"
      contents: "write"
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v3

      - name: 'Java'
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: 'Bygg'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TZ=CET
          ./gradlew build --stacktrace
